export const BUILDINGS = {
  laser: {
    label: 'Laser Turret',
    key: '1',
    cost: 35,
    range: 210,
    fireRate: 0.22,
    damage: 14,
    color: '#ff2bd6',
    description: 'Schnelle Einzelfeuer-Verteidigung.',
  },
  missile: {
    label: 'Missile Turret',
    key: '2',
    cost: 70,
    range: 280,
    fireRate: 0.08,
    damage: 42,
    color: '#ffb000',
    description: 'Langsamer Raketenwerfer mit Flächenschaden.',
  },
  generator: {
    label: 'Generator',
    key: '3',
    cost: 55,
    range: 0,
    fireRate: 0,
    damage: 0,
    color: '#00ff9d',
    description: 'Erhöht Energie- und Data-Einkommen.',
  },
  shield: {
    label: 'Schild',
    key: '4',
    cost: 90,
    range: 0,
    fireRate: 0,
    damage: 0,
    color: '#7d5cff',
    description: 'Schützt den Kern und heilt ihn langsam.',
    hp: 200,
    healRate: 6,
  },
  sniper: {
    label: 'Sniper Turret',
    key: '5',
    cost: 100,
    range: 420,
    fireRate: 0.04,
    damage: 85,
    color: '#00d9ff',
    description: 'Extrem Reichweite, langsamer Schuss, hoher Schaden.',
  },
};
