export const BUILDINGS = {
  laser: {
    label: 'Laser',
    key: '1',
    cost: 30,
    range: 200,
    rate: 4.5,
    damage: 16,
    color: '#ff2bd6',
    description: 'Schneller Turm',
  },
  missile: {
    label: 'Rakete',
    key: '2',
    cost: 55,
    range: 260,
    rate: 1.2,
    damage: 50,
    color: '#ffb000',
    description: 'Flächenschaden',
    splash: 90,
  },
  generator: {
    label: 'Generator',
    key: '3',
    cost: 40,
    range: 0,
    rate: 0,
    damage: 0,
    color: '#00ff9d',
    description: '+5E/s Einkommen',
  },
  shield: {
    label: 'Schild',
    key: '4',
    cost: 65,
    range: 0,
    rate: 0,
    damage: 0,
    color: '#7d5cff',
    description: 'Heilt Kern +8/s',
    hp: 220,
    heal: 8,
  },
  sniper: {
    label: 'Sniper',
    key: '5',
    cost: 80,
    range: 400,
    rate: 0.8,
    damage: 100,
    color: '#00d9ff',
    description: 'Riesige Reichweite',
  },
};

export const UPGRADES = [
  { id: 'dmg', label: 'Schaden +20%', cost: 40, icon: '⚔️', apply: s => { s.upgDmg *= 1.2; } },
  { id: 'rate', label: 'Feuerrate +25%', cost: 50, icon: '🔥', apply: s => { s.upgRate *= 1.25; } },
  { id: 'range', label: 'Reichweite +15%', cost: 45, icon: '🎯', apply: s => { s.upgRange *= 1.15; } },
  { id: 'income', label: 'Einkommen +30%', cost: 35, icon: '💰', apply: s => { s.upgIncome *= 1.3; } },
  { id: 'corehp', label: 'Kern +50 HP', cost: 55, icon: '❤️', apply: s => { s.core.maxHp += 50; s.core.hp = Math.min(s.core.hp + 50, s.core.maxHp); } },
  { id: 'genbonus', label: 'Generator +3E/s', cost: 45, icon: '⚡', apply: s => { s.upgGen += 3; } },
];
