import './style.css';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),hud=document.getElementById('hud');
const K=new Set(),C={bg:'#050816',cyan:'#00d9ff',pink:'#ff2bd6',red:'#ff345d',green:'#00ff9d',yellow:'#ffb000',violet:'#7d5cff',white:'#fff'};let W=0,H=0,S,last=0;
const UPS=[['Pulse Damage','+25% pulse damage',s=>s.mods.dmg*=1.25],['Rapid Fire','+22% fire rate',s=>s.mods.rate*=.78],['Laser Drone','+1 orbit drone',s=>s.drones++],['Swarm Missiles','unlock / upgrade missiles',s=>{s.weapons.missile=true;s.mods.missile*=1.25}],['Lightning Arc','unlock / upgrade chain lightning',s=>{s.weapons.lightning=true;s.mods.lightning*=1.3}],['Magnet Field','bigger XP pickup',s=>s.magnet+=55],['Nano Shield','+35 max HP and heal',s=>{s.player.max+=35;s.player.hp=Math.min(s.player.max,s.player.hp+60)}],['Move Boost','+15% speed',s=>s.mods.speed*=1.15],['XP Greed','+30% XP gain',s=>s.mods.xp*=1.3],['Orbital Cooldown','orbital strike cooldown -30%',s=>s.mods.orb*=.7]];
function resize(){W=canvas.width=innerWidth;H=canvas.height=innerHeight}function rnd(a,b){return a+Math.random()*(b-a)}function d(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function fresh(){S={mode:'menu',time:0,score:0,kills:0,level:1,xp:0,next:12,shake:0,msg:'Enter starten',msgT:0,player:{x:W/2,y:H/2,hp:120,max:120,cd:0,q:0},mods:{dmg:1,rate:1,speed:1,xp:1,missile:1,lightning:1,orb:1},weapons:{missile:false,lightning:false},drones:0,magnet:95,enemies:[],bullets:[],xpDrops:[],fx:[],texts:[],ups:[],spawn:0,bossSpawned:false,mouse:{x:W/2,y:H/2}}}
function start(){fresh();S.mode='play';msg('SURVIVOR PROTOCOL ONLINE')}function msg(t){S.msg=t;S.msgT=2.2}function boom(x,y,c,n=20,p=1){for(let i=0;i<n;i++){let a=Math.random()*7,s=rnd(40,260)*p;S.fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:rnd(.35,1),m:1,c,z:rnd(2,5)})}}function text(x,y,t,c=C.white){S.texts.push({x,y,t,c,l:1.1,m:1.1})}
function spawnEnemy(boss=false){let a=Math.random()*7,far=Math.max(W,H)*.65,x=S.player.x+Math.cos(a)*far,y=S.player.y+Math.sin(a)*far,sec=S.time;if(boss){S.enemies.push({x,y,hp:2200,max:2200,sp:54,sz:42,dmg:28,c:C.white,boss:true,cd:0});msg('BOSS: COREBREAKER TITAN');return}let r=Math.random(),runner=r<.35,tank=sec>80&&r>.78,kami=sec>45&&r>.58&&r<.72,hp=tank?170+sec*.8:kami?45+sec*.35:runner?38+sec*.25:70+sec*.45;S.enemies.push({x,y,hp,max:hp,sp:tank?48:runner?125:kami?155:78,sz:tank?20:runner?10:kami?12:14,dmg:tank?18:kami?35:10,c:tank?C.yellow:kami?C.pink:runner?C.green:C.red,kami,cd:0})}
function levelUp(){S.mode='up';S.ups=[...UPS].sort(()=>Math.random()-.5).slice(0,3);msg('LEVEL UP')}function choose(i){let u=S.ups[i];if(!u)return;u[2](S);S.ups=[];S.mode='play';text(S.player.x,S.player.y-50,u[0],C.green);boom(S.player.x,S.player.y,C.green,80,1.5)}
function nearest(range=9999){return S.enemies.filter(e=>d(e,S.player)<range).sort((a,b)=>d(a,S.player)-d(b,S.player))[0]}function shoot(x,y,t,dmg,c,speed=760,type='pulse'){S.bullets.push({x,y,t,dmg,c,speed,type,trail:[]})}
function update(dt){if(S.mode!=='play')return;S.time+=dt;S.msgT-=dt;S.shake=Math.max(0,S.shake-38*dt);move(dt);spawn(dt);weapons(dt);enemies(dt);bullets(dt);drops(dt);particles(dt);texts(dt);if(S.time>180&&!S.bossSpawned){S.bossSpawned=true;spawnEnemy(true)}if(S.player.hp<=0){S.mode='over';msg('RUN TERMINATED')}}
function move(dt){let dx=0,dy=0;if(K.has('w')||K.has('arrowup'))dy--;if(K.has('s')||K.has('arrowdown'))dy++;if(K.has('a')||K.has('arrowleft'))dx--;if(K.has('d')||K.has('arrowright'))dx++;let l=Math.hypot(dx,dy)||1;S.player.x+=dx/l*270*S.mods.speed*dt;S.player.y+=dy/l*270*S.mods.speed*dt;S.player.x=Math.max(30,Math.min(W-30,S.player.x));S.player.y=Math.max(30,Math.min(H-30,S.player.y));S.player.q-=dt;if(K.has(' ')&&S.player.q<=0){S.player.q=13*S.mods.orb;let x=S.mouse.x,y=S.mouse.y;boom(x,y,C.violet,140,2);S.shake=24;for(const e of S.enemies){let q=Math.hypot(e.x-x,e.y-y);if(q<260)e.hp-=360*(1-q/300)}text(x,y-30,'ORBITAL',C.violet)}}
function spawn(dt){S.spawn-=dt;let rate=Math.max(.06,.42-S.time/420);if(S.spawn<=0){let n=S.time>120?3:S.time>60?2:1;for(let i=0;i<n;i++)spawnEnemy();S.spawn=rate}}
function weapons(dt){S.player.cd-=dt;let t=nearest(460);if(t&&S.player.cd<=0){shoot(S.player.x,S.player.y,t,24*S.mods.dmg,C.cyan,820);S.player.cd=.19*S.mods.rate}for(let i=0;i<S.drones;i++){let ang=S.time*2+i*Math.PI*2/Math.max(1,S.drones),x=S.player.x+Math.cos(ang)*72,y=S.player.y+Math.sin(ang)*72,tar=S.enemies.filter(e=>Math.hypot(e.x-x,e.y-y)<280).sort((a,b)=>d(a,S.player)-d(b,S.player))[0];if(tar&&Math.random()<dt*5)shoot(x,y,tar,15*S.mods.dmg,C.green,760,'drone')}if(S.weapons.missile&&Math.random()<dt*2.2){let m=nearest(520);if(m)shoot(S.player.x,S.player.y,m,70*S.mods.missile,C.yellow,430,'missile')}if(S.weapons.lightning&&Math.random()<dt*2.8){let l=nearest(300);if(l){l.hp-=42*S.mods.lightning;boom(l.x,l.y,C.violet,10);let last=l;for(let i=0;i<3;i++){let nxt=S.enemies.filter(e=>e!==last&&Math.hypot(e.x-last.x,e.y-last.y)<145).sort((a,b)=>Math.hypot(a.x-last.x,a.y-last.y)-Math.hypot(b.x-last.x,b.y-last.y))[0];if(!nxt)break;nxt.hp-=30*S.mods.lightning;last=nxt;boom(nxt.x,nxt.y,C.violet,8)}}}}
function enemies(dt){for(let i=S.enemies.length-1;i>=0;i--){let e=S.enemies[i],dx=S.player.x-e.x,dy=S.player.y-e.y,l=Math.hypot(dx,dy)||1;e.x+=dx/l*e.sp*dt;e.y+=dy/l*e.sp*dt;if(l<e.sz+16){S.player.hp-=e.dmg*dt*(e.kami?8:1);S.shake=Math.max(S.shake,3);if(e.kami){boom(e.x,e.y,e.c,50,1.4);S.player.hp-=e.dmg;S.enemies.splice(i,1);continue}}if(e.hp<=0){S.score+=e.boss?5000:100;S.kills++;let val=e.boss?80:e.sz>18?8:4;S.xpDrops.push({x:e.x,y:e.y,v:val});boom(e.x,e.y,e.c,e.boss?180:28,e.boss?2:1);if(e.boss){S.mode='win';msg('RUN CLEARED')}S.enemies.splice(i,1)}}}
function bullets(dt){for(let i=S.bullets.length-1;i>=0;i--){let b=S.bullets[i];if(!S.enemies.includes(b.t)){S.bullets.splice(i,1);continue}b.trail.push({x:b.x,y:b.y});if(b.trail.length>8)b.trail.shift();let dx=b.t.x-b.x,dy=b.t.y-b.y,l=Math.hypot(dx,dy)||1;b.x+=dx/l*b.speed*dt;b.y+=dy/l*b.speed*dt;if(l<18){if(b.type==='missile'){for(const e of S.enemies){let q=Math.hypot(e.x-b.x,e.y-b.y);if(q<110)e.hp-=b.dmg*(1-q/140)}S.shake=Math.max(S.shake,7);boom(b.x,b.y,b.c,48,1.3)}else{b.t.hp-=b.dmg;boom(b.x,b.y,b.c,7)}S.bullets.splice(i,1)}}}
function drops(dt){for(let i=S.xpDrops.length-1;i>=0;i--){let x=S.xpDrops[i],q=Math.hypot(x.x-S.player.x,x.y-S.player.y);if(q<S.magnet){x.x+=(S.player.x-x.x)/q*420*dt;x.y+=(S.player.y-x.y)/q*420*dt}if(q<24){S.xp+=x.v*S.mods.xp;S.xpDrops.splice(i,1);if(S.xp>=S.next){S.xp-=S.next;S.level++;S.next=Math.floor(S.next*1.28+8);levelUp()}}}}
function particles(dt){for(let i=S.fx.length-1;i>=0;i--){let f=S.fx[i];f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.98;f.vy*=.98;f.l-=dt;if(f.l<=0)S.fx.splice(i,1)}}function texts(dt){for(let i=S.texts.length-1;i>=0;i--){let t=S.texts[i];t.y-=36*dt;t.l-=dt;if(t.l<=0)S.texts.splice(i,1)}}
function draw(){ctx.save();if(S.shake)ctx.translate((Math.random()-.5)*S.shake,(Math.random()-.5)*S.shake);bg();if(S.mode!=='menu'){dropsDraw();enemyDraw();bulletDraw();playerDraw();fxDraw();textDraw()}if(S.mode==='menu')menu();if(S.mode==='up')upDraw();if(S.mode==='over')end('RUN TERMINATED',C.red);if(S.mode==='win')end('COREBREAKER DESTROYED',C.green);ctx.restore();banner();hudDraw()}
function bg(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#040714');g.addColorStop(1,'#03040a');ctx.fillStyle=g;ctx.fillRect(-40,-40,W+80,H+80);ctx.strokeStyle='rgba(0,217,255,.08)';for(let x=0;x<W;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function playerDraw(){ctx.save();ctx.shadowColor=C.white;ctx.shadowBlur=24;ctx.fillStyle=C.white;ctx.beginPath();ctx.arc(S.player.x,S.player.y,17,0,7);ctx.fill();ctx.strokeStyle=C.cyan;ctx.lineWidth=4;ctx.stroke();ctx.restore();for(let i=0;i<S.drones;i++){let a=S.time*2+i*Math.PI*2/Math.max(1,S.drones),x=S.player.x+Math.cos(a)*72,y=S.player.y+Math.sin(a)*72;ctx.fillStyle=C.green;ctx.beginPath();ctx.arc(x,y,8,0,7);ctx.fill()}bar(S.player.x-38,S.player.y+28,76,7,S.player.hp/S.player.max,S.player.hp>40?C.green:C.red)}
function enemyDraw(){for(const e of S.enemies){ctx.save();ctx.shadowColor=e.c;ctx.shadowBlur=18;ctx.fillStyle=e.c;if(e.boss){ctx.beginPath();ctx.arc(e.x,e.y,e.sz,0,7);ctx.fill();ctx.strokeStyle=C.red;ctx.lineWidth=5;ctx.stroke()}else ctx.fillRect(e.x-e.sz,e.y-e.sz,e.sz*2,e.sz*2);ctx.restore();bar(e.x-24,e.y-e.sz-12,48,5,e.hp/e.max,e.hp>e.max*.35?C.white:C.red)}}
function bulletDraw(){for(const b of S.bullets){ctx.save();ctx.strokeStyle=b.c;ctx.globalAlpha=.55;ctx.beginPath();b.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.globalAlpha=1;ctx.shadowColor=b.c;ctx.shadowBlur=14;ctx.fillStyle=b.c;ctx.beginPath();ctx.arc(b.x,b.y,b.type==='missile'?6:4,0,7);ctx.fill();ctx.restore()}}
function dropsDraw(){for(const x of S.xpDrops){ctx.save();ctx.shadowColor=C.cyan;ctx.shadowBlur=10;ctx.fillStyle=C.cyan;ctx.fillRect(x.x-4,x.y-4,8,8);ctx.restore()}}
function fxDraw(){for(const f of S.fx){ctx.globalAlpha=Math.max(0,f.l/f.m);ctx.fillStyle=f.c;ctx.fillRect(f.x,f.y,f.z,f.z);ctx.globalAlpha=1}}function textDraw(){ctx.textAlign='center';ctx.font='800 15px Arial';for(const t of S.texts){ctx.globalAlpha=Math.max(0,t.l/t.m);ctx.fillStyle=t.c;ctx.fillText(t.t,t.x,t.y);ctx.globalAlpha=1}ctx.textAlign='left'}
function bar(x,y,w,h,v,c){ctx.fillStyle='rgba(0,0,0,.75)';ctx.fillRect(x,y,w,h);ctx.fillStyle=c;ctx.fillRect(x,y,w*Math.max(0,Math.min(1,v)),h)}
function menu(){ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle=C.cyan;ctx.font='900 82px Arial';ctx.fillText('NEON',W/2,H/2-90);ctx.fillStyle=C.pink;ctx.font='900 66px Arial';ctx.fillText('SURVIVOR',W/2,H/2-25);ctx.fillStyle=C.white;ctx.font='20px Arial';ctx.fillText('WASD bewegen · Auto-Shoot · Space Orbital Strike · Level Up Builds',W/2,H/2+35);ctx.fillText('Enter startet den Run',W/2,H/2+80);ctx.textAlign='left'}
function upDraw(){ctx.fillStyle='rgba(0,0,0,.82)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle=C.cyan;ctx.font='900 44px Arial';ctx.fillText('LEVEL UP',W/2,115);S.ups.forEach((u,i)=>{let x=W/2-390+i*260,y=185;ctx.fillStyle='rgba(0,217,255,.12)';ctx.fillRect(x,y,230,160);ctx.strokeStyle=C.cyan;ctx.strokeRect(x,y,230,160);ctx.fillStyle=C.white;ctx.font='800 20px Arial';ctx.fillText(`[${i+1}] ${u[0]}`,x+115,y+50);ctx.font='16px Arial';ctx.fillText(u[1],x+115,y+92)});ctx.font='18px Arial';ctx.fillText('Wähle 1, 2 oder 3',W/2,395);ctx.textAlign='left'}
function end(t,c){ctx.fillStyle='rgba(0,0,0,.76)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle=c;ctx.font='900 58px Arial';ctx.fillText(t,W/2,H/2-35);ctx.fillStyle=C.white;ctx.font='22px Arial';ctx.fillText(`Score ${S.score} · Level ${S.level} · Kills ${S.kills} · Time ${Math.floor(S.time)}s`,W/2,H/2+20);ctx.fillText('R Neustart',W/2,H/2+65);ctx.textAlign='left'}
function banner(){if(S.msgT<=0||S.mode==='menu')return;ctx.textAlign='center';ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(W/2-300,82,600,58);ctx.strokeStyle=C.pink;ctx.strokeRect(W/2-300,82,600,58);ctx.fillStyle=C.white;ctx.font='900 24px Arial';ctx.fillText(S.msg,W/2,120);ctx.textAlign='left'}
function hudDraw(){if(S.mode==='menu'){hud.innerHTML='<strong>NEON SURVIVOR</strong><br>Enter starten';return}hud.innerHTML=`<div class="hud-title">NEON SURVIVOR</div><div>Time <b>${Math.floor(S.time)}s</b> · Score <b>${S.score}</b> · Kills <b>${S.kills}</b></div><div>Level <b>${S.level}</b> · XP <b>${Math.floor(S.xp)}/${S.next}</b></div><div>HP <b>${Math.floor(S.player.hp)}/${S.player.max}</b> · Drones <b>${S.drones}</b></div><div>Weapons: Pulse ${S.weapons.missile?'· Missiles':''} ${S.weapons.lightning?'· Lightning':''}</div><hr><div class="small">WASD bewegen · Space Orbital · R Neustart</div>`}
canvas.addEventListener('mousemove',e=>{S.mouse.x=e.clientX;S.mouse.y=e.clientY});canvas.addEventListener('click',()=>{if(S.mode==='menu')start()});addEventListener('keydown',e=>{K.add(e.key.toLowerCase());if(e.key==='Enter'&&S.mode==='menu')start();if(e.key.toLowerCase()==='r')start();if(S.mode==='up'&&['1','2','3'].includes(e.key))choose(+e.key-1)});addEventListener('keyup',e=>K.delete(e.key.toLowerCase()));
function loop(t=0){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}addEventListener('resize',resize);resize();fresh();loop();
