import './style.css';

const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const hud = document.getElementById('hud');

const TILE = 48;
const keys = new Set();
const TYPES = {
  laser: { label: 'Laser Turret', cost: 35, range: 230, rate: 0.33, dmg: 18, color: '#ff2bd6', splash: 0 },
  missile: { label: 'Missile Turret', cost: 75, range: 305, rate: 0.11, dmg: 55, color: '#ffb000', splash: 92 },
  gen: { label: 'Generator', cost: 55, range: 0, rate: 0, dmg: 0, color: '#00ff9d', splash: 0 },
  rail: { label: 'Railgun', cost: 120, range: 410, rate: 0.07, dmg: 145, color: '#7d5cff', splash: 0 },
};
const UPG = [
  { title: 'Laser Overclock', desc: '+25% laser damage', apply: s => s.mods.laser *= 1.25 },
  { title: 'Missile Cluster', desc: '+25% missile splash', apply: s => s.mods.splash *= 1.25 },
  { title: 'Core Shielding', desc: '+22 core HP', apply: s => s.core.hp = Math.min(140, s.core.hp + 22) },
  { title: 'Energy Grid', desc: '+6 income/sec', apply: s => s.baseIncome += 6 },
  { title: 'Commander Rifle', desc: '+40% commander damage', apply: s => s.mods.cmd *= 1.4 },
  { title: 'Cooldown Hack', desc: 'Q/E cooldowns -25%', apply: s => s.mods.cooldown *= 0.75 },
];

let W = 0, H = 0, state, last = 0;
function snap(v){return Math.floor(v/TILE)*TILE+TILE/2;}
function resize(){W=canvas.width=innerWidth;H=canvas.height=innerHeight;if(state){state.core.x=snap(W*.24);state.core.y=snap(H*.5);state.path=path();}}
function path(){return[{x:W+80,y:snap(H*.22)},{x:snap(W*.78),y:snap(H*.22)},{x:snap(W*.78),y:snap(H*.76)},{x:snap(W*.54),y:snap(H*.76)},{x:snap(W*.54),y:snap(H*.36)},{x:snap(W*.35),y:snap(H*.36)},{x:snap(W*.24),y:snap(H*.5)}];}
function fresh(){return{mode:'menu',sel:'laser',energy:220,baseIncome:9,income:9,data:0,score:0,combo:1,comboT:0,shake:0,slowMo:0,core:{x:snap(W*.24),y:snap(H*.5),hp:100,max:100},cmd:{x:snap(W*.34),y:snap(H*.62),hp:100,cd:0,q:0,e:0},buildings:[],enemies:[],shots:[],fx:[],texts:[],path:path(),wave:0,budget:0,timer:0,kills:0,mouse:{x:0,y:0,gx:0,gy:0},msg:'Press Enter',msgT:0,mods:{laser:1,cmd:1,splash:1,cooldown:1},upgrades:[],paused:false};}
function start(){state=fresh();state.mode='play';message('COMMAND ONLINE');nextWave();}
function message(t){state.msg=t;state.msgT=2.4;}
function nextWave(){state.wave++;state.budget=8+state.wave*5;state.timer=0;state.energy+=35+state.wave*7;message(`WAVE ${state.wave}`);boom(W*.86,H*.22,'#ff345d',60,1.5);}
function choices(){state.mode='upgrade';state.upgrades=[...UPG].sort(()=>Math.random()-.5).slice(0,3);message('CHOOSE UPGRADE');}
function choose(i){const u=state.upgrades[i];if(!u)return;u.apply(state);state.upgrades=[];state.mode='play';nextWave();}
function canBuild(t,x,y){const b=TYPES[t];if(!b||state.energy<b.cost)return false;if(Math.hypot(x-state.core.x,y-state.core.y)<TILE*1.5)return false;if(state.buildings.some(o=>o.x===x&&o.y===y))return false;for(let i=1;i<state.path.length;i++){let a=state.path[i-1],b=state.path[i];if(seg(x,y,a.x,a.y,b.x,b.y)<34)return false;}return true;}
function build(){if(state.mode!=='play')return;const t=state.sel,x=state.mouse.gx,y=state.mouse.gy;if(!canBuild(t,x,y)){txt(x,y,'BLOCKED','#ff345d');state.shake=7;return;}state.energy-=TYPES[t].cost;state.buildings.push({t,x,y,cd:0,p:0});boom(x,y,TYPES[t].color,26,1);txt(x,y-22,TYPES[t].label,TYPES[t].color);}
function seg(px,py,x1,y1,x2,y2){const dx=x2-x1,dy=y2-y1,l=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((px-x1)*dx+(py-y1)*dy)/l));return Math.hypot(px-(x1+t*dx),py-(y1+t*dy));}
function enemy(){const r=Math.random(),boss=state.wave%5===0&&state.budget===1,heavy=state.wave>2&&r>.78,fast=r<.32,shield=state.wave>4&&r>.55&&r<.68;const e=boss?{name:'COREBREAKER',hp:620+state.wave*55,sp:37,sz:28,re:90,col:'#fff'}:shield?{name:'SHIELD',hp:125+state.wave*14,sp:49,sz:16,re:22,col:'#00d9ff'}:heavy?{name:'TANK',hp:185+state.wave*18,sp:38,sz:19,re:20,col:'#ff8a00'}:fast?{name:'RUNNER',hp:42+state.wave*5,sp:105+state.wave*3,sz:10,re:10,col:'#00ff9d'}:{name:'DRONE',hp:78+state.wave*8,sp:63+state.wave*2,sz:13,re:12,col:'#ff345d'};state.enemies.push({x:state.path[0].x,y:state.path[0].y+(Math.random()-.5)*20,node:1,hp:e.hp,max:e.hp,speed:e.sp,size:e.sz,reward:e.re,color:e.col,name:e.name,w:Math.random()*6});}
function fire(x,y,target,type='cmd'){const spec=type==='cmd'?{dmg:22*state.mods.cmd,color:'#00d9ff',speed:780,splash:0,type}:{dmg:TYPES[type].dmg*(type==='laser'?state.mods.laser:1),color:TYPES[type].color,speed:type==='missile'?410:type==='rail'?920:720,splash:TYPES[type].splash*state.mods.splash,type};state.shots.push({x,y,target,...spec,trail:[]});}
function boom(x,y,color,n=12,p=1){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=(50+Math.random()*240)*p;state.fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.75,max:1,color,size:2+Math.random()*4});}}
function txt(x,y,text,color='#fff'){state.texts.push({x,y,text,color,life:1.15,max:1.15});}
function abilityQ(){if(state.cmd.q>0||state.data<10)return;state.data-=10;state.cmd.q=8*state.mods.cooldown;state.shake=16;boom(state.cmd.x,state.cmd.y,'#00d9ff',90,1.7);for(const e of state.enemies){const d=Math.hypot(e.x-state.cmd.x,e.y-state.cmd.y);if(d<190){e.hp-=85*state.mods.cmd*(1-d/220);e.speed*=.82;}}txt(state.cmd.x,state.cmd.y-44,'SHOCKWAVE','#00d9ff');}
function abilityE(){if(state.cmd.e>0||state.data<22)return;state.data-=22;state.cmd.e=18*state.mods.cooldown;state.shake=24;const x=state.mouse.x,y=state.mouse.y;boom(x,y,'#ff2bd6',130,2.2);for(const e of state.enemies){const d=Math.hypot(e.x-x,e.y-y);if(d<260)e.hp-=190*(1-d/300);}txt(x,y-30,'ORBITAL STRIKE','#ff2bd6');}
function update(dt){if(state.mode!=='play'||state.paused)return;dt*=state.slowMo>0?.45:1;state.shake=Math.max(0,state.shake-35*dt);state.slowMo=Math.max(0,state.slowMo-dt);state.comboT-=dt;if(state.comboT<=0)state.combo=1;state.msgT-=dt;state.cmd.q=Math.max(0,state.cmd.q-dt);state.cmd.e=Math.max(0,state.cmd.e-dt);const gen=state.buildings.filter(b=>b.t==='gen').length;state.income=state.baseIncome+gen*5;state.energy+=state.income*dt;state.data+=(.9+gen*.55)*dt;moveCommander(dt);waves(dt);turrets(dt);commanderFire(dt);moveEnemies(dt);moveShots(dt);particles(dt);texts(dt);if(state.core.hp<=0){state.core.hp=0;state.mode='over';state.shake=28;message('CORE DESTROYED');}}
function moveCommander(dt){let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;const l=Math.hypot(dx,dy)||1;if(dx||dy){state.cmd.x=Math.max(20,Math.min(W-20,state.cmd.x+dx/l*260*dt));state.cmd.y=Math.max(20,Math.min(H-20,state.cmd.y+dy/l*260*dt));}}
function waves(dt){state.timer+=dt;const rate=Math.max(.1,.48-state.wave*.018);if(state.budget>0&&state.timer>rate){enemy();state.budget--;state.timer=0;}if(state.budget===0&&state.enemies.length===0&&state.timer>1.4){choices();}}
function turrets(dt){for(const b of state.buildings){b.cd-=dt;b.p=Math.max(0,b.p-dt);if(b.t==='gen')continue;const spec=TYPES[b.t];const target=state.enemies.filter(e=>Math.hypot(e.x-b.x,e.y-b.y)<spec.range).sort((a,b)=>b.node-a.node||a.hp-b.hp)[0];if(target&&b.cd<=0){fire(b.x,b.y,target,b.t);b.cd=1/spec.rate;b.p=.22;}}}
function commanderFire(dt){state.cmd.cd-=dt;const t=state.enemies.filter(e=>Math.hypot(e.x-state.cmd.x,e.y-state.cmd.y)<250).sort((a,b)=>a.hp-b.hp)[0];if(t&&state.cmd.cd<=0){fire(state.cmd.x,state.cmd.y,t,'cmd');state.cmd.cd=.18;}}
function moveEnemies(dt){for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i],t=state.path[e.node],dx=t.x-e.x,dy=t.y-e.y,d=Math.hypot(dx,dy)||1;e.w+=dt*7;e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt+Math.sin(e.w)*.18;if(d<12){e.node++;if(e.node>=state.path.length){const dmg=e.name==='COREBREAKER'?45:e.size>18?18:9;state.core.hp-=dmg;state.shake=Math.max(state.shake,dmg*.8);boom(e.x,e.y,e.color,45,1.4);txt(state.core.x,state.core.y-54,`-${dmg} CORE`,'#ff345d');state.enemies.splice(i,1);continue;}}if(Math.hypot(e.x-state.cmd.x,e.y-state.cmd.y)<24){state.cmd.hp-=12*dt;state.shake=Math.max(state.shake,3);}if(e.hp<=0){kill(e);state.enemies.splice(i,1);}}}
function kill(e){const gain=Math.floor(e.reward*state.combo);state.energy+=gain;state.score+=Math.floor(120*state.combo+e.reward*10);state.combo=Math.min(9,state.combo+.18);state.comboT=2.6;state.kills++;state.slowMo=e.name==='COREBREAKER'?.4:state.slowMo;state.shake=Math.max(state.shake,e.name==='COREBREAKER'?24:5);boom(e.x,e.y,e.color,e.name==='COREBREAKER'?140:30,e.name==='COREBREAKER'?2:1);txt(e.x,e.y-24,`+${gain}`,'#00ff9d');}
function moveShots(dt){for(let i=state.shots.length-1;i>=0;i--){const p=state.shots[i];if(!state.enemies.includes(p.target)){state.shots.splice(i,1);continue;}p.trail.push({x:p.x,y:p.y});if(p.trail.length>9)p.trail.shift();const dx=p.target.x-p.x,dy=p.target.y-p.y,d=Math.hypot(dx,dy)||1;p.x+=dx/d*p.speed*dt;p.y+=dy/d*p.speed*dt;if(d<18){if(p.type==='rail'){const ang=Math.atan2(dy,dx);for(const e of state.enemies){if(seg(e.x,e.y,p.x-Math.cos(ang)*700,p.y-Math.sin(ang)*700,p.x+Math.cos(ang)*700,p.y+Math.sin(ang)*700)<22)e.hp-=p.dmg;}state.shake=Math.max(state.shake,9);}else if(p.splash){for(const e of state.enemies){const s=Math.hypot(e.x-p.x,e.y-p.y);if(s<p.splash)e.hp-=p.dmg*(1-s/(p.splash*1.25));}state.shake=Math.max(state.shake,7);}else p.target.hp-=p.dmg;boom(p.x,p.y,p.color,p.splash?40:8,p.splash?1.2:1);state.shots.splice(i,1);}}
}
function particles(dt){for(let i=state.fx.length-1;i>=0;i--){const f=state.fx[i];f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.982;f.vy*=.982;f.life-=dt;if(f.life<=0)state.fx.splice(i,1);}}
function texts(dt){for(let i=state.texts.length-1;i>=0;i--){const t=state.texts[i];t.y-=38*dt;t.life-=dt;if(t.life<=0)state.texts.splice(i,1);}}
function draw(){ctx.save();if(state.shake>0)ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);bg();if(state.mode!=='menu'){drawPath();preview();core();buildings();commander();enemies();shots();fx();floatTexts();}if(state.mode==='menu')menu();if(state.mode==='over')over();if(state.mode==='upgrade')upgrade();ctx.restore();banner();drawHud();}
function bg(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#040714');g.addColorStop(.55,'#071329');g.addColorStop(1,'#03040a');ctx.fillStyle=g;ctx.fillRect(-40,-40,W+80,H+80);ctx.strokeStyle='rgba(0,217,255,.09)';for(let x=0;x<W;x+=TILE){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<H;y+=TILE){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}ctx.fillStyle='rgba(255,43,214,.08)';for(let i=0;i<26;i++){const x=(i*157)%W,h=90+((i*83)%230);ctx.fillRect(x,H-h,32+(i%4)*20,h);}}
function drawPath(){ctx.save();ctx.lineJoin='round';ctx.lineCap='round';ctx.lineWidth=36;ctx.strokeStyle='rgba(255,52,93,.15)';ctx.beginPath();ctx.moveTo(state.path[0].x,state.path[0].y);for(const n of state.path.slice(1))ctx.lineTo(n.x,n.y);ctx.stroke();ctx.lineWidth=4;ctx.strokeStyle='rgba(255,52,93,.85)';ctx.setLineDash([18,16]);ctx.beginPath();ctx.moveTo(state.path[0].x,state.path[0].y);for(const n of state.path.slice(1))ctx.lineTo(n.x,n.y);ctx.stroke();ctx.restore();}
function preview(){if(state.mode!=='play')return;const s=TYPES[state.sel],ok=canBuild(state.sel,state.mouse.gx,state.mouse.gy);ctx.globalAlpha=ok?.75:.25;ctx.fillStyle=ok?s.color:'#ff345d';ctx.fillRect(state.mouse.gx-19,state.mouse.gy-19,38,38);if(s.range){ctx.strokeStyle=s.color;ctx.beginPath();ctx.arc(state.mouse.gx,state.mouse.gy,s.range,0,7);ctx.stroke();}ctx.globalAlpha=1;}
function core(){ctx.save();ctx.shadowColor='#00d9ff';ctx.shadowBlur=30;ctx.fillStyle='#00d9ff';ctx.beginPath();ctx.arc(state.core.x,state.core.y,39,0,7);ctx.fill();ctx.restore();bar(state.core.x-52,state.core.y+52,104,9,state.core.hp/state.core.max,state.core.hp>40?'#00ff9d':'#ff345d');}
function commander(){ctx.save();ctx.shadowColor='#fff';ctx.shadowBlur=22;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(state.cmd.x,state.cmd.y,16,0,7);ctx.fill();ctx.strokeStyle='#00d9ff';ctx.lineWidth=4;ctx.stroke();ctx.restore();ctx.strokeStyle='rgba(0,217,255,.25)';ctx.beginPath();ctx.arc(state.cmd.x,state.cmd.y,250,0,7);ctx.stroke();}
function buildings(){for(const b of state.buildings){const s=TYPES[b.t];ctx.save();ctx.shadowColor=s.color;ctx.shadowBlur=18+b.p*70;ctx.fillStyle=s.color;if(b.t==='gen'){ctx.beginPath();ctx.moveTo(b.x,b.y-23);ctx.lineTo(b.x+23,b.y+18);ctx.lineTo(b.x-23,b.y+18);ctx.closePath();ctx.fill();}else if(b.t==='rail'){ctx.translate(b.x,b.y);ctx.rotate(.78);ctx.fillRect(-7,-29,14,58);ctx.fillRect(-25,-7,50,14);}else{ctx.fillRect(b.x-19,b.y-19,38,38);ctx.fillStyle='#050816';ctx.fillRect(b.x-8,b.y-8,16,16);}ctx.restore();}}
function enemies(){for(const e of state.enemies){ctx.save();ctx.shadowColor=e.color;ctx.shadowBlur=18;ctx.fillStyle=e.color;if(e.name==='COREBREAKER'){ctx.beginPath();ctx.arc(e.x,e.y,e.size,0,7);ctx.fill();ctx.strokeStyle='#ff345d';ctx.lineWidth=5;ctx.stroke();}else ctx.fillRect(e.x-e.size,e.y-e.size,e.size*2,e.size*2);ctx.restore();bar(e.x-24,e.y-e.size-15,48,5,e.hp/e.max,e.hp>e.max*.35?'#fff':'#ff345d');}}
function shots(){for(const p of state.shots){ctx.save();ctx.strokeStyle=p.color;ctx.lineWidth=p.type==='rail'?5:2;ctx.globalAlpha=.55;ctx.beginPath();p.trail.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.stroke();ctx.globalAlpha=1;ctx.shadowColor=p.color;ctx.shadowBlur=18;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.type==='missile'?6:4,0,7);ctx.fill();ctx.restore();}}
function fx(){for(const f of state.fx){ctx.globalAlpha=Math.max(0,f.life/f.max);ctx.fillStyle=f.color;ctx.fillRect(f.x,f.y,f.size,f.size);ctx.globalAlpha=1;}}
function floatTexts(){ctx.textAlign='center';ctx.font='800 16px Arial';for(const t of state.texts){ctx.globalAlpha=Math.max(0,t.life/t.max);ctx.fillStyle=t.color;ctx.fillText(t.text,t.x,t.y);ctx.globalAlpha=1;}ctx.textAlign='left';}
function bar(x,y,w,h,v,c){ctx.fillStyle='rgba(0,0,0,.75)';ctx.fillRect(x,y,w,h);ctx.fillStyle=c;ctx.fillRect(x,y,w*Math.max(0,Math.min(1,v)),h);}
function menu(){ctx.fillStyle='rgba(0,0,0,.48)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#00d9ff';ctx.font='900 86px Arial';ctx.fillText('NEON',W/2,H/2-90);ctx.fillStyle='#ff2bd6';ctx.font='900 68px Arial';ctx.fillText('COMMAND',W/2,H/2-25);ctx.fillStyle='#fff';ctx.font='20px Arial';ctx.fillText('WASD Commander · Q Shockwave · E Orbital Strike · Build Turrets',W/2,H/2+34);ctx.fillText('Enter oder Klick startet',W/2,H/2+82);ctx.textAlign='left';}
function over(){ctx.fillStyle='rgba(0,0,0,.75)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#ff345d';ctx.font='900 68px Arial';ctx.fillText('CORE DESTROYED',W/2,H/2-40);ctx.fillStyle='#fff';ctx.font='22px Arial';ctx.fillText(`Score ${state.score} · Wave ${state.wave} · Kills ${state.kills}`,W/2,H/2+16);ctx.fillText('R Neustart',W/2,H/2+62);ctx.textAlign='left';}
function upgrade(){ctx.fillStyle='rgba(0,0,0,.78)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#00d9ff';ctx.font='900 44px Arial';ctx.fillText('SYSTEM UPGRADE',W/2,120);state.upgrades.forEach((u,i)=>{const x=W/2-390+i*260,y=190;ctx.fillStyle='rgba(0,217,255,.12)';ctx.fillRect(x,y,230,150);ctx.strokeStyle='#00d9ff';ctx.strokeRect(x,y,230,150);ctx.fillStyle='#fff';ctx.font='800 20px Arial';ctx.fillText(`[${i+1}] ${u.title}`,x+115,y+45);ctx.font='16px Arial';ctx.fillText(u.desc,x+115,y+86);});ctx.font='18px Arial';ctx.fillText('Wähle 1, 2 oder 3',W/2,390);ctx.textAlign='left';}
function banner(){if(state.mode!=='play'||state.msgT<=0)return;ctx.save();ctx.globalAlpha=Math.min(1,state.msgT/.5);ctx.textAlign='center';ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(W/2-265,90,530,60);ctx.strokeStyle='#ff345d';ctx.strokeRect(W/2-265,90,530,60);ctx.fillStyle='#fff';ctx.font='900 28px Arial';ctx.fillText(state.msg,W/2,129);ctx.restore();}
function drawHud(){if(state.mode==='menu'){hud.innerHTML='<strong>NEON COMMAND</strong><br>Enter starten';return;}hud.innerHTML=`<div class="hud-title">NEON COMMAND</div><div>Score <b>${state.score}</b> · Combo <b>x${state.combo.toFixed(1)}</b></div><div>Wave <b>${state.wave}</b> · Gegner <b>${state.enemies.length+state.budget}</b> · Kills <b>${state.kills}</b></div><div>Energy <b>${Math.floor(state.energy)}</b> · Income <b>${state.income.toFixed(1)}/s</b> · Data <b>${Math.floor(state.data)}</b></div><div>Core <b>${Math.floor(state.core.hp)}%</b> · Commander <b>${Math.max(0,Math.floor(state.cmd.hp))}%</b></div><hr><div class="build ${state.sel==='laser'?'active':''}">[1] Laser ${TYPES.laser.cost}</div><div class="build ${state.sel==='missile'?'active':''}">[2] Missile ${TYPES.missile.cost}</div><div class="build ${state.sel==='gen'?'active':''}">[3] Generator ${TYPES.gen.cost}</div><div class="build ${state.sel==='rail'?'active':''}">[4] Railgun ${TYPES.rail.cost}</div><div class="small">WASD move · Q Shock ${Math.ceil(state.cmd.q)} · E Strike ${Math.ceil(state.cmd.e)}</div>`;}
canvas.addEventListener('mousemove',e=>{state.mouse.x=e.clientX;state.mouse.y=e.clientY;state.mouse.gx=snap(e.clientX);state.mouse.gy=snap(e.clientY);});
canvas.addEventListener('click',()=>state.mode==='menu'?start():build());
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key==='Enter'&&state.mode==='menu')start();if(e.key==='r'||e.key==='R')start();if(e.code==='Space')state.paused=!state.paused;if(state.mode==='upgrade'&&['1','2','3'].includes(e.key))choose(Number(e.key)-1);if(e.key==='1')state.sel='laser';if(e.key==='2')state.sel='missile';if(e.key==='3')state.sel='gen';if(e.key==='4')state.sel='rail';if(e.key.toLowerCase()==='q')abilityQ();if(e.key.toLowerCase()==='e')abilityE();});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function frame(t=0){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(frame);}state=fresh();addEventListener('resize',resize);resize();frame();
